AWSTemplateFormatVersion: '2010-09-09'
Description: Creata a EC2 instance with a Security group SSH access
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
 MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-098e39bafa7e7303d
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
MyVolume:
  Type: AWS::EC2::Volume
  Properties:
    AvailabilityZone: !GetAtt MyInstance.AvailabilityZone
    Size: 25
MyVolumeAttachment:
  Type: AWS::EC2::VolumeAttachment
  Properties:
    AvailabilityZone: !Ref MyInstance
    VolumeId: !Ref MyVolume
    Device: /dev/sdf
    
